-- Insert the master hand list / matrix --
INSERT INTO
    hand_combos (combo_name)
VALUES
    ('AA'),
    ('AKs'),
    ('AQs'),
    ('AJs'),
    ('ATs'),
    ('A9s'),
    ('A8s'),
    ('A7s'),
    ('A6s'),
    ('A5s'),
    ('A4s'),
    ('A3s'),
    ('A2s'),
    ('AKo'),
    ('KK'),
    ('KQs'),
    ('KJs'),
    ('KTs'),
    ('K9s'),
    ('K8s'),
    ('K7s'),
    ('K6s'),
    ('K5s'),
    ('K4s'),
    ('K3s'),
    ('K2s'),
    ('AQo'),
    ('KQo'),
    ('QQ'),
    ('QJs'),
    ('QTs'),
    ('Q9s'),
    ('Q8s'),
    ('Q7s'),
    ('Q6s'),
    ('Q5s'),
    ('Q4s'),
    ('Q3s'),
    ('Q2s'),
    ('AJo'),
    ('KJo'),
    ('QJo'),
    ('JJ'),
    ('JTs'),
    ('J9s'),
    ('J8s'),
    ('J7s'),
    ('J6s'),
    ('J5s'),
    ('J4s'),
    ('J3s'),
    ('J2s'),
    ('ATo'),
    ('KTo'),
    ('QTo'),
    ('JTo'),
    ('TT'),
    ('T9s'),
    ('T8s'),
    ('T7s'),
    ('T6s'),
    ('T5s'),
    ('T4s'),
    ('T3s'),
    ('T2s'),
    ('A9o'),
    ('K9o'),
    ('Q9o'),
    ('J9o'),
    ('T9o'),
    ('99'),
    ('98s'),
    ('97s'),
    ('96s'),
    ('95s'),
    ('94s'),
    ('93s'),
    ('92s'),
    ('A8o'),
    ('K8o'),
    ('Q8o'),
    ('J8o'),
    ('T8o'),
    ('98o'),
    ('88'),
    ('87s'),
    ('86s'),
    ('85s'),
    ('84s'),
    ('83s'),
    ('82s'),
    ('A7o'),
    ('K7o'),
    ('Q7o'),
    ('J7o'),
    ('T7o'),
    ('97o'),
    ('87o'),
    ('77'),
    ('76s'),
    ('75s'),
    ('74s'),
    ('73s'),
    ('72s'),
    ('A6o'),
    ('K6o'),
    ('Q6o'),
    ('J6o'),
    ('T6o'),
    ('96o'),
    ('86o'),
    ('76o'),
    ('66'),
    ('65s'),
    ('64s'),
    ('63s'),
    ('62s'),
    ('A5o'),
    ('K5o'),
    ('Q5o'),
    ('J5o'),
    ('T5o'),
    ('95o'),
    ('85o'),
    ('75o'),
    ('65o'),
    ('55'),
    ('54s'),
    ('53s'),
    ('52s'),
    ('A4o'),
    ('K4o'),
    ('Q4o'),
    ('J4o'),
    ('T4o'),
    ('94o'),
    ('84o'),
    ('74o'),
    ('64o'),
    ('54o'),
    ('44'),
    ('43s'),
    ('42s'),
    ('A3o'),
    ('K3o'),
    ('Q3o'),
    ('J3o'),
    ('T3o'),
    ('93o'),
    ('83o'),
    ('73o'),
    ('63o'),
    ('53o'),
    ('43o'),
    ('33'),
    ('32s'),
    ('A2o'),
    ('K2o'),
    ('Q2o'),
    ('J2o'),
    ('T2o'),
    ('92o'),
    ('82o'),
    ('72o'),
    ('62o'),
    ('52o'),
    ('42o'),
    ('32o'),
    ('22') 
ON CONFLICT DO NOTHING; -- If an exception is raised, do nothing

-- Create an example raw JSONB value --
INSERT INTO raw_ranges (doc) VALUES
    ('{
    "profilename": "Example F3Bet",
    "range": {
        "call": ["AKs", "AQs"],
        "raise": ["QQ", "JJ"]
    },
    "description": "Example range for documentation.",
    "type": "F3Bet",
    "stack": "40bb",
    "position": "MP",
    "game_type": "cash",
    "is_template": true,
    "owner_id": null
    }'::jsonb);

-- Convert and insert data from JSONB to relational --
INSERT INTO range_profiles (
    profile_name,
    description,
    range_type,
    stack_size,
    position,
    is_template,
    owner_id
)
SELECT
    doc->>'profilename',
    doc->>'description',
    doc->>'type',
    doc->>'stack',
    doc->>'position',
    (doc->>'is_template')::boolean,
    NULLIF(doc->>'owner_id', '')::uuid
FROM raw_ranges
ON CONFLICT DO NOTHING;

-- Give each profile their ranges --
INSERT INTO profile_combos (profile_id, combo, play)
SELECT DISTINCT
    rp.id,
    elem.val,
    elem.play
FROM range_profiles rp
JOIN raw_ranges r ON r.doc->>'profilename' = rp.profile_name
CROSS JOIN LATERAL (
    SELECT jsonb_array_elements_text(r.doc->'range'->'call') AS val, 'call' AS play
    UNION ALL
    SELECT jsonb_array_elements_text(r.doc->'range'->'raise') AS val, 'raise' AS play
) AS elem
JOIN hand_combos hc ON hc.combo_name = elem.val;