# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - poker-browser-toolbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'      

      - name: Install npm packages - server
        run: |
          cd backend
          npm install       
      
      - name: Install npm packages, build then copy files - client
        run: |
          npm install
          npm run build
          cp -r ./build ./backend/public
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: poker-toolbox
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: poker-toolbox

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'poker-browser-toolbox'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E6C213455CFE453594CBDF83A12B37C3 }}
          package: .
